config/routes.rb
Rails.application.routes.draw do

  resources :users, :divisions

  root 'welcome#index'

end

app/models/division.rb
class Division < ActiveRecord::Base
	has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :division

	validates_presence_of :username, :battletag
	validates :email, confirmation: true
	validates :password, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
	def index
		@divisions = Division.all
	end

	def show
		@division = Division.find(params[:id])
		@users = User.where(division_id: params[:id]).order(points: :desc)
	end

	def new
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@allsvenskan = User.where(division_id: '1').order(points: :desc)
		@superettan = User.where(division_id: '2').order(points: :desc)
		@division = Division.all
		@users = User.all
	end

	def new
	end

	def show
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(user_params)

		if @user.save
			redirect_to @user
		else
			render 'new'
		end
	end

	private

	def user_params
	params.require(:user).permit(:username, :battletag, :password, :email, :user_region)
	end
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@divisions = Division.all

  	@users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/divisions/index.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Rank</th>
  </tr>
 
  <% @divisions.each do |division| %>
    <tr>
      <td><%= link_to(division.title, division) %></td>
      <td><%= division.rank %></td>
    </tr>
  <% end %>

app/views/divisions/new.html.erb
test

app/views/divisions/show.html.erb
<%= @division.title %>

<table>
	<tr>
		<th>username</th>
		<th>wins</th>
		<th>losses</th>
		<th>draws</th>
		<th>points</th>
		<th>played</th>
	</tr>
	<% @users.each do |user| %>
	<tr>
		<td><%= link_to(user.username, user) %></td>
		<td><%= user.won %></td>
		<td><%= user.loss %></td>
		<td><%= user.draw %></td>
		<td><%= user.points %></td>
		<td><%= user.won + user.loss + user.draw %></td>
	</tr>
	<% end %>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DuckingDubstep</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<nav>
	<ul>
		<li>home</li>
		<li>ranking</li>
		<li>users</li>
		<li>faq</li>
		<li>contact</li>
	</ul>
</nav>
<body>

<%= yield %>
this is a test
</body>
</html>

app/views/users/index.html.erb
<% @division.each do |division| %>
<table>
	<h2><%= division.title %></h2>
		<th>username</th>
		<th>wins</th>
		<th>losses</th>
		<th>draws</th>
		<th>points</th>
	<% @users.where(division_id: division.id).each do |user| %>
	<tr>
		<td><%= link_to(user.username, user) %></td>
		<td><%= user.won %></td>
		<td><%= user.loss %></td>
		<td><%= user.draw %></td>
		<td><%= user.points %></td>
	</tr>
	<% end %>
</table>
<% end %>

<table>
	<th>username</th>
	<th>wins</th>
	<th>losses</th>
	<th>draws</th>
	<th>points</th>
	<th>email</th>
	<th>battletag</th>
	<% @users.each do |user| %>
	<tr>
		<td><%= link_to(user.username, user) %></td>
		<td><%= user.won %></td>
		<td><%= user.loss %></td>
		<td><%= user.draw %></td>
		<td><%= user.points %></td>
		<td><%= user.email %></td>
		<td><%= user.battletag %></td>
	</tr>
	<% end %>
</table>

app/views/users/new.html.erb
<%= form_for :user, url: users_path do |f| %>
	<p>
		<%= f.label :username %>
		<%= f.text_field :username %>
	</p>
	<p>
		<%= f.label :battletag %>
		<%= f.text_field :battletag %>
	</p>
	<p>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</p>
	<p>
		<%= f.radio_button(:user_region, "US") %>
		<%= f.label :user_region, "US", :value => "us" %>
		<%= f.radio_button(:user_region, "EU") %>
		<%= f.label :user_region, "EU", :value => "eu" %>
		<%= f.radio_button(:user_region, "AU") %>
		<%= f.label :user_region, "AU", :value => "au" %>
	</p>
	<p>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :email_confirmation %>
		<%= f.text_field :email_confirmation %>
	</p>
	<p>
		<%= f.submit %> 
	</p>
<% end %>

app/views/users/show.html.erb
<table>
	<th>username</th>
	<th>wins</th>
	<th>losses</th>
	<th>draws</th>
	<th>points</th>
	<th>email</th>
	<th>battletag</th>
	<tr>
		<td><%= @user.username %></td>
		<td><%= @user.won %></td>
		<td><%= @user.loss %></td>
		<td><%= @user.draw %></td>
		<td><%= @user.points %></td>
		<td><%= @user.email %></td>
		<td><%= @user.battletag %></td>
	</tr>
</table>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<table>
  <tr>
    <th>Title</th>
    <th>Rank</th>
  </tr>
 
  <% @divisions.each do |division| %>
    <tr>
      <td><%= division.title %></td>
      <td><%= division.rank %></td>
    </tr>
  <% end %>

<table>
  <tr>
    <th>Title</th>
    <th>Rank</th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.battletag %></td>
      <td><%= user.won %></td>
      <td><%= user.loss %></td>
      <td><%= user.draw %></td>
      <td><%= user.division_id %></td>
    </tr>
  <% end %>